package com.gang.lightpollution.client.renderer;

import com.mojang.blaze3d.pipeline.TextureTarget;
import net.minecraft.core.BlockPos;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;

/**
 * Camera-local anchor state for the VanillaDI-style GPU occupancy cache.
 *
 * <p>The cache itself is populated from the rendered depth and normal buffers
 * in {@code gemini_kill_post_light_voxelize.fsh}. Keeping only the anchor
 * state on the CPU is deliberate: {@code BlockState.getShape()} cannot see
 * cutout-model holes in fences, iron bars, or trapdoors.</p>
 *
 * <p>The anchor is a whole-block world position. Upstream VanillaDI adds
 * {@code fract(markerPosition)} to its grid origin because its volume is
 * camera-relative and needs a fixed alignment reference; this port instead
 * anchors the volume in world space and reprojects the rolling cache by whole
 * blocks, so any fractional term would slide every subvoxel boundary across
 * world geometry each frame and make thin occluders shimmer.</p>
 */
final class SpellLightVoxelGrid {
    static final int SIZE = 64;
    /** VanillaDI layout: 128 block columns x 16 RGBA texels per block. */
    static final int TEXTURE_WIDTH = 2048;
    static final int TEXTURE_HEIGHT = 2048;

    /** VanillaDI rolls the 64-block volume whenever the marker crosses a block. */
    private static final int REANCHOR_BLOCKS = 1;

    @Nullable
    private BlockPos origin;
    @Nullable
    private BlockPos uploadedOrigin;
    private int uploadedTextureId = -1;
    private int buildTextureId = -1;

    /**
     * Selects the current camera-local grid origin. The previously committed
     * origin remains available until the GPU pass finishes so the shader can
     * reproject the rolling cache without losing geometry outside this frame's
     * depth buffer.
     *
     * @return true when the anchor or destination texture changed
     */
    boolean prepareForGpu(Vec3 cameraPosition, TextureTarget target) {
        BlockPos requestedOrigin = originFor(cameraPosition);
        boolean originChanged = !requestedOrigin.equals(origin);
        int textureId = target.getColorTextureId();
        boolean targetChanged = textureId != buildTextureId;

        if (originChanged) {
            origin = requestedOrigin;
        }
        if (targetChanged) {
            buildTextureId = textureId;
        }
        return originChanged || targetChanged;
    }

    /** True when the destination texture is the one currently being built. */
    boolean targetMatches(TextureTarget target) {
        return buildTextureId == target.getColorTextureId();
    }

    /** True when the selected GPU origin already matches the camera anchor. */
    boolean originMatches(Vec3 cameraPosition) {
        return origin != null && origin.equals(originFor(cameraPosition));
    }

    /** Publishes a completed GPU voxelizer frame as the active cache. */
    void commitGpuUpload(TextureTarget target) {
        if (origin != null) {
            uploadedOrigin = origin;
            uploadedTextureId = target.getColorTextureId();
            buildTextureId = uploadedTextureId;
        }
    }

    /** Invalidates the old cache after either GPU cache render target is recreated. */
    void invalidateGpuUpload() {
        uploadedOrigin = null;
        uploadedTextureId = -1;
        buildTextureId = -1;
    }

    /** Origin of the cache currently sampled by the lighting pass. */
    float originX() {
        return uploadedOrigin == null ? 0.0F : uploadedOrigin.getX();
    }

    float originY() {
        return uploadedOrigin == null ? 0.0F : uploadedOrigin.getY();
    }

    float originZ() {
        return uploadedOrigin == null ? 0.0F : uploadedOrigin.getZ();
    }

    /** Origin currently being generated by the GPU voxelizer. */
    float currentOriginX() {
        return origin == null ? 0.0F : origin.getX();
    }

    float currentOriginY() {
        return origin == null ? 0.0F : origin.getY();
    }

    float currentOriginZ() {
        return origin == null ? 0.0F : origin.getZ();
    }

    /** True once the lighting pass can sample a coherent GPU volume. */
    boolean isReady() {
        return uploadedOrigin != null && uploadedTextureId == buildTextureId
                && uploadedTextureId >= 0;
    }

    /** True only between selecting a new anchor and committing its GPU cache. */
    boolean isTransitioning() {
        return origin != null && uploadedOrigin != null && !origin.equals(uploadedOrigin);
    }

    void release() {
        origin = null;
        uploadedOrigin = null;
        uploadedTextureId = -1;
        buildTextureId = -1;
    }

    private static BlockPos originFor(Vec3 cameraPosition) {
        return new BlockPos(
                align(cameraPosition.x) - SIZE / 2,
                align(cameraPosition.y) - SIZE / 2,
                align(cameraPosition.z) - SIZE / 2);
    }

    private static int align(double value) {
        return Math.floorDiv((int) Math.floor(value), REANCHOR_BLOCKS) * REANCHOR_BLOCKS;
    }
}
